lang: ko-KR, en-UK

title: haehejheyju

author:
  name: Haeju Kim
  social:
    github: haehejheyju

copyright:             © 2024. All rights reserved.

permalink:             none

paginate:              10
paginate_path:         /page-:num/
excerpt_separator:     <!--more-->

accent_image:          /assets/img/sidebar.jpg
accent_color:          rgb(179,165,128)
theme_color:           rgb(21,87,6)

google_fonts:          Domine:700|EB+Garamond:400,400i,700,700i
font:                  EB+Garamond, Domine, serif
font_heading:          EB+Garamond, Domine, serif

- scope:
      path:            assets/**
    values:
      sitemap:         false

- scope:
      type:            featured_categories
    values:
      seo:
        type:          WebPage

  no_mark_external:    false
  no_push_state:       false
  no_drawer:           false
  no_navbar:           false
  no_search:           false
  no_inline_css:       false
  no_page_style:       false
  no_break_layout:     true
  no_toc:              false
  no_third_column:     false
  no_large_headings:   false
  no_structured_data:  false
  no_theme_color:      false
  no_breadcrumbs:      false

  use_lsi:             true
  cookies_banner:      true
  advertise:           true
  hide_dates:          false
  hide_last_modified:  false

  dark_mode:
    always:            false
    dynamic:           true
    sunrise:           6
    sunset:            18
    icon:              true

  offline:
    enabled:           false
    cache_version:     1
    precache_assets:
      - /assets/img/swipe.svg

collections:
 featured_categories:
   permalink: /:Maths/
   output: true

   permalink: /:Cryptography/
   output: true

   permalink: /:Programming/
   output: true

exclude:
  - .jekyll-cache
  - .sass-cache
  - '*.toml'
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules

include:
  - .well-known
  - LICENSE.md

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jemoji

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed

jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar.jpg
    posts:
      layout: post
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar.jpg
    projects:
      layout: project
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar.jpg
      links:
        - title: Project Link
          url: https://example.com

feed:
  categories:
    - Maths
    - Cryptography
    - Programming

favicon: /assets/icons/faviconlogo.ico
app_touch_icon: /assets/img/faviconlogo.png